//OpCommandController.js

(function (OpCommandController) {
    
    var fs = require("fs-extra");
    var path = "Z:\\test2.json";

    OpCommandController.init = function (app) {
        
        // The execution Id should be generated by the app and remember it everytime it executes some operation. 
        // To get the result, pass the executionId and I will fetch the value of it from the airlock in which the output file will have an executionID.

        app.get("/api/OpCommands/:executionId", function (req, res) {
            
           var executionId = req.params.executionId;
            // This is where you need to fetch the data from the Airlock and return the result based on the id that you have got.
                                  
            fs.readJson(path, function (err, outPutObject) {
                
                if (err) {
                    res.status(400).send({ errorNo : -1, errorMsg : "No File present still. Call me back sometime", errorCode : "FAIL", error : err });                    
                }
                else {
                    res.set("Content-Type", "application/json");
                    res.status(200).send(outPutObject);
                    console.log(outPutObject) // => 0.1.3 
                }
            })            
        });
    };

})(module.exports);